Creating a Grails app is about as simple as could be - once you have installed Grails, simply run the http://docs.grails.org/latest/ref/Command%20Line/create-app.html[`create-app`] command:

[source, bash]
----
$ grails create-app myApp
----

You can optionally specify a default package for the application:

[source, bash]
----
$ grails create-app com.example.myApp
----

Finally, you can optionally specify a http://docs.grails.org/latest/guide/profiles.html[Profile] for your Grails app. Profiles are available for many common application types, including `rest-api`, `angular`, `react`, and others, and you can even create your own.

To view of a list of what profiles are available, use the http://docs.grails.org/latest/ref/Command%20Line/list-profiles.html[`list-profiles`] command.

[source, bash]
----
$ grails list-profiles

| Available Profiles
--------------------
* angular - A profile for creating applications using AngularJS
* rest-api - Profile for REST API applications
* base - The base profile extended by other profiles
* angular2 - A profile for creating Grails applications with Angular 2
* plugin - Profile for plugins designed to work across all profiles
* profile - A profile for creating new Grails profiles
* react - A profile for creating Grails applications with a React frontend
* rest-api-plugin - Profile for REST API plugins
* web - Profile for Web applications
* web-plugin - Profile for Plugins designed for Web applications
* webpack - A profile for creating applications with node-based frontends using webpack
----

To use a profile, specify its name preceded by the `-profile` flag:

[source, bash]
----
grails create-app myApp -profile rest-api
----

You may optionally specify a package and version (defaults to `org.grails.profiles` and the current version of the profile)

[source, bash]
----
grails create-app myApp -profile org.grails.profiles:react:1.0.2
----

TIP: When you create an app without `-profile` the default profile used is the `web` profile.
