By default, Grails configures an in-memory H2 database, which is dropped and recreated every time the app is restarted. This will be sufficient for our purposes in this guide, however, you can easily change this to a local database instance by configuring your own datasource. We'll use MySQL as an example.

Edit `build.gradle`

[source,groovy]
.build.gradle
----
dependencies {
    //...

    runtime 'mysql:mysql-connector-java:5.1.40' <1>
----
<1> Add the MySQL JDBC driver as a dependency

WARNING: Be sure to add the MySQL dependency to the `dependencies` section of the `build.gradle` file, and not the `buildscript`/`dependencies` section. The former is for application dependencies (needed for at compile time, runtime, or testing), whereas the `buildscript` `dependencies` is for those needed as part of the Gradle build process (managing static assets, for example).

Edit `application.yml`

[source,yml]
.grails-app/conf/application.yml
----
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: com.mysql.jdbc.Driver   <1>
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    username: sa
    password: testing
environments:
    development:
        dataSource:
            dbCreate: update
            url: jdbc:mysql://127.0.0.1:3306/myapp <2>
----
<1> Change the `driverClassName` and `dialect` to MySQL settings
<2> This assumes you have a local MySQL instance with a database named `myapp`


