For our `Vehicle` class, it doesn't really make sense that `make` and `model` are plain Strings, since models should actually be associated with makes. Let's update our domain model to be more robust.

Create two new domain classes:


[source, bash]
----
$ ./grailsw create-domain-class demo.Make

| Created grails-app/domain/demo/Make.groovy
| Created src/test/groovy/demo/Make.groovy

$ ./grailsw create-domain-class demo.Model

| Created grails-app/domain/demo/Model.groovy
| Created src/test/groovy/demo/Model.groovy
----

Edit these two files with the following content:

[source,groovy]
.grails-app/domain/demo/Make.groovy
----
include::{sourceDir}/grails-app/domain/demo/Make.groovy[]
----

[source,groovy]
.grails-app/domain/demo/Model.groovy
----
include::{sourceDir}/grails-app/domain/demo/Model.groovy[]
----

NOTE: The `belongsTo` property is one of several properties that GORM uses to determine associations between domain classes. Others include `hasMany` and `hasOne`. For more information please see the http://gorm.grails.org/6.0.x/hibernate/manual/#gormAssociation[GORM documentation].

Now, update `Vehicle.groovy` to use the new `Make` and `Model` classes instead of `String`.

[source,groovy]
.grails-app/domain/demo/Vehicle.groovy
----
include::{sourceDir}/grails-app/domain/demo/Vehicle.groovy[]
----

[source, groovy]
----
def vehicle = Vehicle.findByName('pickup')
if(vehicle) {
    println vehicle.model // e.g, 'Titan'
    println vehicle.make // e.g, 'Nissan'
}
----

Grails (via GORM) will now create three tables in our database, for our three domain classes, and create the necessary associations between the tables. Run the app again and open the DB Console to view the new tables.

