GSP pages have access to a rich set of tags. We've seen a few in action already. You can get much more detail on the available GSP tags (including how to define your own custom tags) from the Grails documentation.

Let's soup up our `index.gsp` page a bit with some GSP tags.

Edit `grails-app/views/home/index.gsp`

[source,xml]
.grails-app/views/home/index.gsp
----
<html>
<html>
<head>
    <meta name="layout" content="public"/>
    <title>Home Page</title>
</head>
<body>

<div id="content" role="main">
    <section class="row colset-2-its">
        <h1>Welcome ${name}!</h1>
        <g:if test="${flash.message}"> //<1>
            <div class="message" role="status">${flash.message}</div>
        </g:if>

        <p>There are ${vehicleTotal} vehicles in the database.</p>

        <ul>
        <g:each in="${Vehicle.list()}" var="vehicle">
            <li>${vehicle.name}</li>
        </g:each>
        </ul>

        <g:form action="updateName" style="margin: 0 auto; width:320px"> //<2>
            <g:textField name="name" value="" />
            <g:submitButton name="Update name" />
        </g:form>

    </section>
</div>

</body>
</html>
----
<1> Rather than rendering `flash.message` regardless of whether it exists, we use the `<g:if>` tag to test if there is a message, and then render the message (using some custom styling).
<2> Replace the plain HTML `<form>` tags with their GSP equivalents.

Let's take a closer look at `<g:if>`.

[source,xml]
----
    <g:if test="${isThisTrue}}>
        Some content
    </g:if>
----

GSP tags can optionally accept attributes, such as `test` in this example. Different tags require different types of attributes, but typically you will end up passing a Groovy Expression like in this example. Anything Groovy code between the `${` and `}` will be evaluated (on the server) and the result will be substituted on the rendered page.

TIP: You can use Groovy Expressions anywhere on the GSP page, not just in tags. See the `${flash.message}` in our `index.gsp` page.

Other tag attributes might accept plain strings or numbers. E.g, `<g:form action="updateName">`

A GSP tag can also optionally include a body. In the case of `<g:if>`, the body will only be rendered if the `test` expression evaluates to true (following the http://docs.groovy-lang.org/latest/html/documentation/#Groovy-Truth[Groovy Truth] convention). Other GSP tags (like `<g:form>`) simply include the body within the resulting HTML output.

There are GSP tags for iteration as well - a very useful one is `<g:each>`. Let's try it out:

[source,xml]
.grails-app/views/home/index.gsp
----
<%@ page import="com.example.Vehicle" %> //<1>
<html>
<!-- ... -->
        <p>There are ${vehicleTotal} vehicles in the database.</p>

        <ul>
            <g:each in="${Vehicle.list()}" var="vehicle">
                <li>${vehicle.name}</li>
            </g:each>
        </ul>

<!-- ... -->
----
<1> This is a JSP-style expression that allows executing arbitrary Groovy code (without rendering a result). We're using it here to import our `Vehicle` class. This is *highly* discouraged - we'll explain why shortly.

The `<g:each>` tag iterates through a collection of objects, provided by the `in` attribute. `var` sets the name for each object in the collection. Grails will iterate through the collection (in this case, the list of `Vehicles` returned by `Vehicle.list()`) and render the body of the `<g:each>` tag for every item.

IMPORTANT: This sort of code is a *bad idea* - we are accessing our domain model (`Vehicle`) directly from our view, which tightly couples two separate parts of the application, and in general leads to very messy code. The better way to accomplish this feature is to get the `Vehicle` list in the `HomeController.index` action, and add the list to our model object (the one being passed to `respond`). Then we could refer to the list in the same way that we access `name` and `vehicleTotal`. Go ahead and change the controller and view to use this better approach - the completed project has this change already made if you need help.