Now that you've created (or downloaded) your Grails project, it's time to run it and see what Grails has already given you.

If you have a local installation of Grails, you can run the app using the http://docs.grails.org/latest/ref/Command%20Line/run-app.html[run-app] command from within your project:

[source, bash]
----
$ cd myApp/
----

**Run the App without Grails Installed**

Thanks to the http://docs.grails.org/latest/guide/introduction.html#whatsNewGrailsWrapper[Grails Wrapper], as of Grails version 3.2.3 or later, you can run any Grails command without having
Grails installed. If you download it from the http://start.grails.org[Grails Application Forge], the Grails Wrapper is included too.

[source, bash]
----
$ ./grailsw run-app
----

**Run the App with Grails installed**

If you have Grails installed in your machine, simply type:

[source, bash]
----
$ grails run-app
----

**Run the App with Grails Interactive Mode**

You can also use Grails' http://docs.grails.org/latest/guide/commandLine.html#interactiveMode[Interactive Mode] to run the Grails runtime,
from which you can issue any Grails command without waiting for the runtime to spin up for each task.
In this guide we will be preferring the Grails wrapper for most commands.

[source, bash]
----
$ ./grailsw

| Enter a command name to run. Use TAB for completion:
grails>run-app      //you can shutdown the app with the stop-app command
----

**Run the App with Gradle**

Finally, because Grails is built upon https://projects.spring.io/spring-boot/[Spring Boot] and https://gradle.org/[Gradle], you can also use Spring Boot commands like `bootRun` to interact with your Grails application. Like for Grails you do not have to download and install Gradle, this will happen automatically using the the Gradle Wrapper (`gradlew`)

[source, bash]
----
$ ./gradlew bootRun
----

Once you've run any of those commands, Grails will launch your application using an embedded Tomcat server, and make it available (by default) at `http://localhost:8080`.

[source, bash]
----
$ ./grailsw run-app

| Running application...
Grails application running at http://localhost:8080 in environment: development
----
