gettingStarted: 
  title: Getting Started
  requirements: What you will need
  howto: How to complete the guide
creatingTheApp:
  title: Creating your Grails App
  installing: Installing Grails
  createApp: Create the App
runningTheApp:
  title: Running the App
domainClasses:
  title: Domain Classes
  creatingDomainClass: Creating a Domain Class
  databaseConsole: DB Console
  expandDomain: Expanding the Domain Model
  bootstrap: Bootstrapping Data
  datasource: Datasources
  console: Grails Console
controllers:
  title: Controllers
  urlMappings: URL Mappings
  scaffolding: Scaffolding
  respond: Render a response
views:
  title: Views
  gsp: GSP
  assetPipeline: Asset Pipeline
services:
  title: Services
testing:
  title: Testing your App
deployment:
  title: Deploying your App